package com.example.myedgelighting.utils

object CommonKeys {
    val CUSTOM_STRING = "custom_string"
    val ANIM_DURATION = "animationDuration"
    val ANIM_SPEED = "animationSpeed"
    val OVERLAY_KEY = "overlay_permission_granted"
    val SERVICE_KEY = "service_running"
    val ANIM_POSITION = "animationPos"
    val Corner_Radius = "CornerRadius"
    val STROKE_WIDTH = "StrokeWidth"
    val SYMBOL_SIZE = "SymbolSize"
    val Service = "first"
    val NOTCH_WIDTH = "NOTCH_WIDTH"
    val NOTCH_HEIGHT = "NOTCH_HEIGHT"
    val NOTCH_RADIUS = "NOTCH_RADIUS"
    val notchType = "notchType"
    val SelectId = "lastSelectedId"
    val SelectFragment = "lastFragmentPosition"
    val SelectSymbol = "lastSymbolSelected"
    val SelectSymbolStyle = "SelectedSymbolStyle"
    val SelectedAnimationMode = "SelectedAnimationMode"
    val SelectedColor = "SelectedColor"
    val NotchHeight = "Notch_Height"
    val NotchWidth = "Notch_Width"
    val NotchCRadius = "Notch_CRadius"
    val NotchX = "Notch_X"
    val NotchY = "Notch_Y"
    val SelectedColorMode = "SelectedColorMode"
    val SelectedColor1 = "SelectedColor1"
    val SelectedColor2 = "SelectedColor2"
    val LAST_SELECTED_BUTTON_ID = "LAST_SELECTED_BUTTON_ID"
    val LAST_SELECTED_ALPHABET_ID = "LAST_SELECTED_Alphabet_ID"
    val DISPLAY_MODE_KEY = "DISPLAY_MODE_KEY"
    val DISPLAY_NOTCH_KEY = "DISPLAY_NOTCH_KEY"
    val DISPLAY_COLOR_KEY = "DISPLAY_COLOR_KEY"
    val SelectedColor3 = "SelectedColor3"
    val LAST_SELECTED_POSITION = "LAST_SELECTED_POSITION"
    val StartColor1 = "StartColor1"
    val EndColor1 = "EndColor1"
    val StartColor2 = "StartColor2"
    val EndColor2 = "EndColor2"
    val SavedColor = "SavedColor"
    val ColorMode = "colorMode"
    val SelectedSymbol = "SelectedSymbol"
}